# Generated by Django 5.2.10 on 2026-01-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kasb nomi')),
                ('photo', models.ImageField(upload_to='professions/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Kasb haqida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kasb',
                'verbose_name_plural': 'Kasblar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', "O'qituvchi"), ('student', "O'quvchi")], default='student', max_length=20, verbose_name='Rol'),
        ),
    ]
