# Generated by Django 5.2.10 on 2026-01-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_message_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Yashash manzili'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/birth_certificates/', verbose_name="Tug'ilganlik haqida guvohnoma"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan kuni"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_cards/', verbose_name='ID karta/Pasport'),
        ),
    ]
