# Generated by Django 5.2.10 on 2026-01-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_product_homeworksubmission_coin_awarded_activitylog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='duration',
            field=models.PositiveIntegerField(default=1, verbose_name='Davomiyligi (daqiqa)'),
        ),
    ]
