# Generated by Django 5.2.10 on 2026-01-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_videolesson_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolesson',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Davomiyligi (daqiqa)'),
        ),
    ]
