# Generated by Django 5.2.10 on 2026-01-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_videolesson_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cointransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productpurchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productlike',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='productlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productpurchase',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='CoinTransaction',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
        migrations.DeleteModel(
            name='ProductLike',
        ),
        migrations.DeleteModel(
            name='ProductPurchase',
        ),
    ]
