# Generated by Django 5.2.10 on 2026-01-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_section_lesson_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube yoki Vimeo havolasi', null=True, verbose_name='Video havolasi'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube havolasi'),
        ),
    ]
