# Generated by Django 5.2.10 on 2026-01-23 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_videolesson_video_url_alter_videolesson_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('image', models.ImageField(blank=True, null=True, upload_to='help_requests/', verbose_name='Rasm')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', "Ko'rib chiqilmoqda"), ('resolved', 'Hal qilindi'), ('closed', 'Yopildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Admin javobi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Yordam so'rovi",
                'verbose_name_plural': "Yordam so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
