# Generated by Django 5.2.10 on 2026-01-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allow_retry',
            field=models.BooleanField(default=False, verbose_name='Qayta ishlashga ruxsat'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('lesson', 'Dars yuzasidan'), ('midterm', 'Oraliq test'), ('practice', 'Tajriba oshirish')], default='lesson', max_length=20, verbose_name='Test turi'),
        ),
    ]
