# Generated by Django 5.2.10 on 2026-01-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_test_allow_retry_test_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_cards/', verbose_name='ID karta / Pasport'),
        ),
    ]
