# Generated by Django 5.2.10 on 2026-01-24 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_id_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Chegirma nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('discount_type', models.CharField(choices=[('percentage', 'Foiz'), ('fixed', "Qat'iy summa")], default='percentage', max_length=20, verbose_name='Chegirma turi')),
                ('discount_value', models.IntegerField(verbose_name='Chegirma qiymati')),
                ('min_coins_required', models.IntegerField(default=0, verbose_name='Minimal coin talab')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish sanasi')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='accounts.profession', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Chegirma',
                'verbose_name_plural': 'Chegirmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
