# Generated by Django 5.2.10 on 2026-01-26 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, verbose_name='Qurilma ID')),
                ('device_name', models.CharField(max_length=200, verbose_name='Qurilma nomi')),
                ('device_type', models.CharField(max_length=50, verbose_name='Qurilma turi')),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brauzer')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operatsion tizim')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Joylashuv')),
                ('is_trusted', models.BooleanField(default=False, verbose_name='Ishonchli qurilma')),
                ('first_login', models.DateTimeField(auto_now_add=True, verbose_name='Birinchi kirish')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Oxirgi kirish')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi qurilmasi',
                'verbose_name_plural': 'Foydalanuvchi qurilmalari',
                'ordering': ['-last_login'],
                'unique_together': {('user', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True, verbose_name='Session kaliti')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
                ('expires_at', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.userdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi sessiyasi',
                'verbose_name_plural': 'Foydalanuvchi sessiyalari',
                'ordering': ['-last_activity'],
            },
        ),
    ]
