# Generated by Django 5.2.10 on 2026-01-26 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userdevice_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLDeploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('file_name', models.CharField(max_length=100, verbose_name='Fayl nomi')),
                ('html_content', models.TextField(verbose_name='HTML kodi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('views_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deploys', to='accounts.profession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HTML Deploy',
                'verbose_name_plural': 'HTML Deploylar',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'file_name')},
            },
        ),
    ]
