# Generated by Django 5.2.10 on 2026-01-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_htmldeploy'),
    ]

    operations = [
        # First remove the old unique constraint
        migrations.AlterUniqueTogether(
            name='htmldeploy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='htmldeploy',
            name='deploy_type',
            field=models.CharField(choices=[('html', 'HTML fayl'), ('project', 'Loyiha (ZIP)')], default='html', max_length=20, verbose_name='Turi'),
        ),
        migrations.AddField(
            model_name='htmldeploy',
            name='entry_file',
            field=models.CharField(default='index.html', max_length=100, verbose_name='Asosiy fayl'),
        ),
        migrations.AddField(
            model_name='htmldeploy',
            name='folder_name',
            field=models.CharField(default='project', max_length=100, verbose_name='Papka nomi'),
        ),
        migrations.AlterField(
            model_name='htmldeploy',
            name='html_content',
            field=models.TextField(blank=True, null=True, verbose_name='HTML kodi'),
        ),
        migrations.RemoveField(
            model_name='htmldeploy',
            name='file_name',
        ),
        # Now add the new unique constraint
        migrations.AlterUniqueTogether(
            name='htmldeploy',
            unique_together={('user', 'folder_name')},
        ),
    ]
