# Generated by Django 5.2.10 on 2026-01-26 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_htmldeploy_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hisobot nomi')),
                ('report_type', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('custom', 'Maxsus')], default='monthly', max_length=20, verbose_name='Hisobot turi')),
                ('date_from', models.DateField(verbose_name='Boshlanish sanasi')),
                ('date_to', models.DateField(verbose_name='Tugash sanasi')),
                ('total_users', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('total_teachers', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0, verbose_name='Yangi foydalanuvchilar')),
                ('total_courses', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('total_videos', models.IntegerField(default=0)),
                ('total_tests', models.IntegerField(default=0)),
                ('total_homeworks', models.IntegerField(default=0)),
                ('new_enrollments', models.IntegerField(default=0, verbose_name='Yangi yozilishlar')),
                ('test_submissions', models.IntegerField(default=0, verbose_name='Test topshiruvlar')),
                ('homework_submissions', models.IntegerField(default=0, verbose_name='Vazifa topshiruvlar')),
                ('video_views', models.IntegerField(default=0, verbose_name="Video ko'rishlar")),
                ('total_deploys', models.IntegerField(default=0)),
                ('new_deploys', models.IntegerField(default=0, verbose_name='Yangi loyihalar')),
                ('deploy_views', models.IntegerField(default=0)),
                ('total_coins', models.IntegerField(default=0)),
                ('coins_earned', models.IntegerField(default=0, verbose_name='Ishlangan coinlar')),
                ('coins_spent', models.IntegerField(default=0, verbose_name='Sarflangan coinlar')),
                ('total_certificates', models.IntegerField(default=0)),
                ('new_certificates', models.IntegerField(default=0, verbose_name='Yangi sertifikatlar')),
                ('total_activities', models.IntegerField(default=0, verbose_name='Jami harakatlar')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='PDF fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tizim hisoboti',
                'verbose_name_plural': 'Tizim hisobotlari',
                'ordering': ['-date_to', '-created_at'],
            },
        ),
    ]
