# Generated by Django 5.2.10 on 2026-01-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_systemreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('all', 'Barchaga'), ('students', "O'quvchilarga"), ('teachers', "O'qituvchilarga"), ('personal', 'Shaxsiy'), ('system', 'Tizim xabari'), ('payment', "To'lov eslatmasi"), ('motivation', "Rag'batlantirish"), ('warning', 'Ogohlantirish'), ('achievement', 'Yutuq'), ('reminder', 'Eslatma'), ('recommendation', 'Tavsiya'), ('security', 'Xavfsizlik')], default='all', max_length=20),
        ),
    ]
