# Generated by Django 5.2.10 on 2026-01-27 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='allow_late',
            field=models.BooleanField(default=True, verbose_name='Kech topshirishga ruxsat'),
        ),
        migrations.AddField(
            model_name='homework',
            name='late_penalty',
            field=models.IntegerField(default=10, verbose_name='Kechikish jarimasi (%)'),
        ),
        migrations.AddField(
            model_name='homework',
            name='max_score',
            field=models.IntegerField(default=100, verbose_name='Maksimal ball'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='feedback_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_feedback/', verbose_name='Izoh fayli'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='Kech topshirilgan'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='revision_count',
            field=models.IntegerField(default=0, verbose_name='Qayta topshirish soni'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Versiya'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('reviewing', "Ko'rib chiqilmoqda"), ('revision', 'Qayta ishlash kerak'), ('accepted', 'Qabul qilindi'), ('graded', 'Baholangan')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='HomeworkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('file', models.FileField(blank=True, null=True, upload_to='homework_chat/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_messages', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.homeworksubmission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homework_revisions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='accounts.homeworksubmission')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
