"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from dotenv import load_dotenv
import os

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)fxm1vrhjd!nfp46v$6v2*_bx&*7t8=mg&ic(6w8#ubez4y+&u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'accounts',
    'blog',
    'ai_yordamchi',
    'coin',
]

# ============================
# 🎨 JAZZMIN — DEV LMS STYLE
# ============================

JAZZMIN_SETTINGS = {
    "site_title": "IT Creative LMS Admin",
    "site_header": "IT Creative LMS 🚀",
    "site_brand": "IT Creative",
    "welcome_sign": "Xush kelibsiz, Developer 😎",
    "copyright": "Suyunov Husan | IT Creative",

    # LOGO (agar static/images/logo.png bo‘lsa)
    "site_logo": "images/logo.png",
    "login_logo": "images/logo.png",
    "site_icon": "images/favicon.ico",

    "search_model": [
        "accounts.CustomUser",
        "accounts.Profession",
        "accounts.Lesson",
    ],

    # 🔝 TOP MENU
    "topmenu_links": [
        {"name": "🌐 Sayt", "url": "/", "new_window": True},
        {"name": "📊 Statistika", "url": "admin:index"},
        {"name": "🎥 IT Creative", "url": "https://youtube.com/@ITCreative", "new_window": True},
        {"model": "accounts.CustomUser"},
    ],

    # 👤 USER MENU
    "usermenu_links": [
        {"name": "🌐 Saytga o‘tish", "url": "/", "new_window": True},
        {"model": "accounts.CustomUser"},
    ],

    # 📂 SIDEBAR TARTIBI
    "order_with_respect_to": [
        "accounts",
        "accounts.CustomUser",
        "accounts.Profession",
        "accounts.CourseEnrollment",
        "accounts.Lesson",
        "accounts.VideoLesson",
        "accounts.Homework",
        "accounts.HomeworkSubmission",
        "accounts.Test",
        "accounts.TestQuestion",
        "accounts.TestResult",
        "accounts.Certificate",
        "accounts.CoinTransaction",
    ],

    # 🎯 ICONS (DEV STYLE)
    "icons": {
        "auth": "fas fa-shield-alt",

        "accounts.CustomUser": "fas fa-user-astronaut",
        "accounts.Profession": "fas fa-laptop-code",
        "accounts.CourseEnrollment": "fas fa-user-plus",

        "accounts.Lesson": "fas fa-chalkboard-teacher",
        "accounts.VideoLesson": "fas fa-play-circle",

        "accounts.Homework": "fas fa-tasks",
        "accounts.HomeworkSubmission": "fas fa-file-code",

        "accounts.Test": "fas fa-brain",
        "accounts.TestQuestion": "fas fa-question-circle",
        "accounts.TestResult": "fas fa-chart-line",

        "accounts.Certificate": "fas fa-certificate",
        "accounts.CoinTransaction": "fas fa-coins",
    },

    "default_icon_parents": "fas fa-layer-group",
    "default_icon_children": "fas fa-dot-circle",

    "show_sidebar": True,
    "navigation_expanded": True,
    "related_modal_active": True,

    # FORM STYLE
    "changeform_format": "vertical_tabs",
    "changeform_format_overrides": {
        "accounts.CustomUser": "collapsible",
        "accounts.Profession": "horizontal_tabs",
    },

    # CUSTOM STYLE
    "custom_css": "admin/custom.css",
    "custom_js": None,

    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "cyborg",
    "dark_mode_theme": "cyborg",

    "navbar": "navbar-dark bg-gradient-primary",
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-primary",

    "accent": "accent-info",

    "navbar_fixed": True,
    "sidebar_fixed": True,
    "footer_fixed": False,

    "sidebar_nav_child_indent": True,
    "sidebar_disable_expand": False,

    "button_classes": {
        "primary": "btn btn-info",
        "secondary": "btn btn-secondary",
        "success": "btn btn-success",
        "warning": "btn btn-warning",
        "danger": "btn btn-danger",
        "info": "btn btn-outline-info",
    },

    "actions_sticky_top": True,
}


AUTH_USER_MODEL = 'accounts.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.BirthdayCheckMiddleware',
    'accounts.middleware.UpdateLastActivityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'accounts.middleware.BlockedUserMiddleware',
    'accounts.middleware.PaymentCheckMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JS, Images)

STATIC_URL = '/static/'

# bu yerda sening static papkang (development paytida)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# collectstatic qilganda hamma fayllar shu yerga yig‘iladi
STATIC_ROOT = BASE_DIR / "staticfiles"


# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
