# Generated by Django 5.2.10 on 2026-01-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_yordamchi', '0002_update_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'Creative AI')], max_length=20),
        ),
    ]
