# Generated by Django 5.2.10 on 2026-01-20 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(verbose_name='Mahsulot haqida')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Rasm')),
                ('coin_price', models.IntegerField(verbose_name='Narxi (Coin)')),
                ('stock', models.IntegerField(default=0, verbose_name='Omborda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Tizimga kirdi'), ('logout', 'Tizimdan chiqdi'), ('like_post', 'Postga like bosdi'), ('comment_post', 'Postga izoh qoldirdi'), ('like_product', 'Mahsulotga like bosdi'), ('comment_product', 'Mahsulotga izoh qoldirdi'), ('submit_homework', 'Vazifa topshirdi'), ('homework_graded', 'Vazifasi baholandi'), ('submit_test', 'Test topshirdi'), ('watch_video', "Video ko'rdi"), ('enroll_course', 'Kursga yozildi'), ('purchase_product', 'Mahsulot sotib oldi'), ('earn_coins', 'Coin oldi')], max_length=30)),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faollik',
                'verbose_name_plural': 'Faolliklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coin.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mahsulot izohi',
                'verbose_name_plural': 'Mahsulot izohlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_spent', models.IntegerField(verbose_name='Sarflangan coin')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Yetkazildi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='coin.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xarid',
                'verbose_name_plural': 'Xaridlar',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='coin.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mahsulot like',
                'verbose_name_plural': 'Mahsulot likelari',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
