# Generated by Django 5.2.10 on 2026-01-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cointransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Coin tranzaksiya', 'verbose_name_plural': 'Coin tranzaksiyalar'},
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='action',
            field=models.CharField(choices=[('add', 'Qo‘shildi'), ('remove', 'Ayirildi'), ('purchase', 'Xarid qilindi')], default='add', max_length=20, verbose_name='Amal turi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Tizimga kirdi'), ('logout', 'Tizimdan chiqdi'), ('like_post', 'Postga like bosdi'), ('comment_post', 'Postga izoh qoldirdi'), ('like_product', 'Mahsulotga like bosdi'), ('comment_product', 'Mahsulotga izoh qoldirdi'), ('submit_homework', 'Vazifa topshirdi'), ('homework_graded', 'Vazifasi baholandi'), ('submit_test', 'Test topshirdi'), ('watch_video', 'Video ko‘rdi'), ('enroll_course', 'Kursga yozildi'), ('purchase_product', 'Mahsulot sotib oldi'), ('earn_coins', 'Coin oldi')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Coin miqdori'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sabab'),
        ),
        migrations.AlterField(
            model_name='product',
            name='coin_price',
            field=models.PositiveIntegerField(verbose_name='Narxi (Coin)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Omborda'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='coins_spent',
            field=models.PositiveIntegerField(verbose_name='Sarflangan coin'),
        ),
    ]
