# Generated by Django 5.2.10 on 2026-01-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_alter_cointransaction_options_cointransaction_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlike',
            name='coin_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
